config/routes.rb
Blogger::Application.routes.draw do
  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors

  resources :author_sessions, only: [ :new, :create, :destroy ]

  match 'login'  => 'author_sessions#new'
  match 'logout' => 'author_sessions#destroy'
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :body, :tag_list, :image
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image, styles: { large: "500x500>", medium: "300x300>", thumb: "50x30>" }

  def tag_list
    tags.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by_name(name) }
    self.tags = new_or_found_tags
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  # attr_accessible :title, :body

  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author_name, :body
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :taggings
  has_many :articles, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])

    @comment = Comment.new
    @comment.article_id = @article.id

  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    @article.save

    flash.notice = "Article '#{@article.title}' Created!"

    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id]) 
  end

  def update
    @article = Article.find(params[:id])
    @article.update_attributes(params[:article])

    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    flash.notice = "Article '#{@article.title}' Deleted!"

    redirect_to articles_path
  end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:username], params[:password])
      redirect_back_or_to(articles_path, message: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, message: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  before_filter :require_login, except: [:new, :create]

  before_filter :zero_authors_or_authenticated, only: [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/authors_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  attr_accessible :new, :create, :destroy
  def new
  end

  def create
    if login(params[:username], params[:password])
      redirect_back_or_to(articles_path, message: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, message: 'Logged out!')
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_login, except: [:create]
  def create
    @comment = Comment.new(params[:comment])
    @comment.article_id = params[:article_id]

    @comment.save

    redirect_to article_path(@comment.article)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :require_login, only: [:destroy]
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <% if @article.image.exists? %>
      <%= image_tag @article.image.url(:medium) %><br />
    <% end %>
    <%= f.label :image, "Attach a new Image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <p><%= link_to "Cancel", :back %></p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>
<div class="container">
<div class"row">
<div class="span12">
<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <% if article.image.exists? %>
        <%= image_tag article.image.url(:thumb) %>
      <% end %>
      <%= link_to article.title, article_path(article), class: 'article_title', id: "article_#{article.id}" %>
    </li>
  <% end %>
</ul>
</div>
</div>
</div>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<h2><%= link_to "<< Back to Articles List", articles_path %></h2>

<div class="container">
<% if @article.image.exists? %>
<p><%= image_tag @article.image.url(:large) %></p>
<% end %>
<p><%= @article.body %></p>
<br />
<p>Posted <%= distance_of_time_in_words(@article.created_at, Time.now) %> ago by <%= current_user.username %></p>
<br />
<p>
  Tags:
  <% @article.tags.each do|tag| %>
    <%= link_to tag.name, tag_path(tag), class: "btn" %>
  <% end %>

  <% if logged_in? %>
  <%= link_to "edit", edit_article_path(@article), class: "btn btn-small btn-primary"%>
  <%= link_to "delete", article_path(@article), class: "btn btn-small btn-danger", method: :delete, confirm: "Really delete the article?" %>
  <% end %>
</p>


<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>

<%= link_to "<< Back to Articles List", articles_path %>
</div>

app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :username %>
    <%= text_field_tag :username %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>
<div class="container">

<table class="table table-striped table-bordered table-condensed">
  <thead>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.username %></td>
    <td><%= author.email %></td>
    <td><%= link_to 'Show', author, class: "btn btn-primary btn-small" %></td>
    <td><%= link_to 'Edit', edit_author_path(author), class: "btn btn-small" %></td>
    <td><%= link_to 'Destroy', author, class: "btn btn-danger btn-small", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path, class: "btn btn-primary"%>
</div>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <p>
      <b>Username:</b>
      <%= @author.username %>
    </p>

    <p>
      <b>Email:</b>
      <%= @author.email %>
    </p>
  </div>
<%= link_to 'Edit', edit_author_path(@author), class: "btn btn-primary" %> |
<%= link_to 'Back', authors_path, class: "btn" %>
</div>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your Name" %><br />
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Your Comment" %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/header' %>

<p class="flash"><%= flash.notice %></p>
<div class="row">
  <%= yield %>
</div>

<%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer">
  <% if logged_in? %>
    <%= "Logged in as #{current_user.username}" %>
    <%= link_to "(logout)", logout_path %>
  <% else %>
    <%= link_to "(login)", login_path %>
  <% end %>
</footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Blogly", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Authors",    authors_path %></li>
          <li><%= link_to "Tags", tags_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul>
  <% @tags.each do |tag| %>
    <li><%= link_to tag.name, tag_path(tag) %></li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>